### ISSUE TITLE
0.3.1 Not Released on crates.io?

### ISSUE THREAD

**Issue by theory** [supabase/wrappers#259]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The [v0.3.1](https://github.com/supabase/wrappers/releases/tag/v0.3.1) release says it incremented the pgrx dependency to 0.11.3, but the [latest on crates.io](https://crates.io/crates/supabase-wrappers) says it's 0.11.2 (and the wrapper version is 0.1.17, so the versions confuse me).

**Comment by imor** [comment]
The versions are different because these are two different crates. The one on crates.io is `supabase-wrappers`, which is the framework crate. It wraps Postgres API (using pgrx) and exposes a higher level API to write a foreign data wrapper. This crate has version 0.1.17. 

The `wrappers` crate is not published on crates.io. It contains a variety of foreign data wrappers written using the framework crate. It generates the shared lib extension we use in Postgres. It's version is 0.3.1.

If you need `supabase-wrappers` which depends on pgrx 0.11.3 I can release version 0.1.18.

**Comment by burmecia** [comment]
[supabase-wrappers v0.1.18](https://crates.io/crates/supabase-wrappers) is already released on crates.io
