### ISSUE TITLE
timestamptz and json should work for WIT

### ISSUE THREAD

**Issue by akacase** [supabase/wrappers#373]
# Bug report

`timestamptz` and `json` aren't implemented, even though exposed via the `TypeOid` and `Cell` enums.

## Describe the bug

No matter the implementation, upon matching `column.type_oid()` in a match block, it will throw without fail on two needed
column types for us:

`timestamptz` and `json`

## To Reproduce

Create a foreign table with a json or timestamptz column defined and accept input from an API that should match those types, postgres will spit out these errors:

```
2024-11-30 21:36:54.885 EST [16441] STATEMENT:  select * from users;
2024-11-30 21:40:20.688 EST [16923] ERROR:  not implemented
```

## Expected behavior

The implementation should match and parse the content with the interfaces provided with the Wasm Interface.

## System information

- OS: macOS
- Postgres: 16 (with wrappers built and installed locally)
- Rust: 1.83.0

**Comment by burmecia** [comment]
Thanks for reporting this issue.

This issue is caused by `timestamptz` type missing in the [`type_oid()` function](https://github.com/supabase/wrappers/blob/29b5c8d2f7b64b7b9b3d1ec5441303a82e5b19bf/wrappers/src/fdw/wasm_fdw/host/mod.rs#L104). We will fix it soon.

For the `json` type, we're actually using `jsonb` internally because it is recommended by Postgres team to as `json` replacement. So for the `json` type in WIT we should use corresponding `jsonb` column type as Postgres table column type.

**Comment by burmecia** [comment]
thank you @akacase for the suggestion. Yes the Wasm wrappers are working for JSON-related APIs only, which we think could cover most of our external data sources. And `jiff` is a great datetime tool and we'd like to use it, but somehow we already used `chrono` in many native wrappers, so we probably won't introduce another similar datetime lib, but thanks again for the great ideas.
